/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java401_code_challenges;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
